### ISSUE TITLE
中文复杂推理那一项对比的模型是不是有问题

### ISSUE THREAD

**Issue by piekey1994** [Neutralzz/BiLLa#1]
BELLE-LLaMA-Ext-7B
Linly-Chinese-LLaMA-7b-hf
这两个似乎是预训练模型，而对比的是Billa的sft模型，是否不恰当

**Comment by Neutralzz** [comment]
> BELLE-LLaMA-Ext-7B Linly-Chinese-LLaMA-7b-hf 这两个似乎是预训练模型，而对比的是Billa的sft模型，是否不恰当

是不恰当的，这部分评测会由pandallm的同学持续补充，可以关注一下他们的Git~
