### ISSUE TITLE
为什么要分阶段训练（二、三）

### ISSUE THREAD

**Issue by liangzz1991** [Neutralzz/BiLLa#10]
你好！第二阶段类似instructgpt的sft，然后第三阶段改成对话的方式+一些高质量（dolly alpaca-gpt4）的数据的对话形式。其实二三阶段大多数数据都一样，只是形式不同。。为什么不直接将二三阶段合并，将第二阶段的任务数据<prompt,target>也直接改成chat的形式，二三在一起多训几个epoch。。作者有对比过，合并和分阶段的结果差异嘛。。

**Comment by Neutralzz** [comment]
第二阶段不是sft，是lm的继续训练，训练加入任务数据，强化lm对nlp任务的理解。

**Comment by Neutralzz** [comment]
该问题已经整理到FAQ，还有相关问题可以再打开issue~
