### ISSUE TITLE
逻辑推理能较弱

### ISSUE THREAD

**Issue by lucasjinreal** [Neutralzz/BiLLa#11]
![image](https://github.com/Neutralzz/BiLLa/assets/21303438/9b78d6ed-000f-4fd5-b503-d92ae10680cc)

**Comment by lucasjinreal** [comment]
![image](https://github.com/Neutralzz/BiLLa/assets/21303438/c8c4aac6-39c1-483f-8e49-3319c248b310)

**Comment by Neutralzz** [comment]
一般来说，我们要构建起评测集，跟其他模型一起整体比较哦~
推理能力的增强也是相对的，比如billa对比chatglm-6b在代码和解题能力的提升，对比belle和pandallm在c3数据集上的提升。

**Comment by lucasjinreal** [comment]
@Neutralzz 不过我对比的通常是13b的模型，7b理论上也比较难达到比较合理的水准。楼主有试过训练一下13b看看效果怎么样嘛

**Comment by lucasjinreal** [comment]
@Neutralzz 不过我对比的通常是13b的模型，7b理论上也比较难达到比较合理的水准。楼主有试过训练一下13b看看效果怎么样嘛

**Comment by Neutralzz** [comment]
相关问题已经整理到FAQ，所以先关闭该issue啦~有问题随时可以再打开~
