### ISSUE TITLE
多轮对话数据处理

### ISSUE THREAD

**Issue by lucasjinreal** [Neutralzz/BiLLa#12]
楼主有训过BELLE的多轮对话数据吗，看DataPreprocessor里面的逻辑貌似没有处理conversations

**Comment by Neutralzz** [comment]
没有

**Comment by lucasjinreal** [comment]
好的，那我在BiLLa的基础上加多轮train一下看看。另外我看sft里面你用的数据集中英文多，多国语言欠缺，有计划加更多国语言以及更多数学逻辑推理类语料吗

**Comment by Neutralzz** [comment]
都想计划，但是不方便 (╥_╥)
