### ISSUE TITLE
请问，执行的embedding_convert.py过程出现AssertionError: The sum of weights (-3801.82958984375) is wrong怎么解决？

### ISSUE THREAD

**Issue by chk4991** [Neutralzz/BiLLa#13]

**Comment by Neutralzz** [comment]
重新检查你原始llama的权重

**Comment by hopeforus** [comment]
最后程序运行完成出现这个数字是不是就代表权重合作成功？

**Comment by Neutralzz** [comment]
参考issue#8

**Comment by ShadowPower** [comment]
我有相同的问题，CPU是6800H，没有独显

**Comment by wwngh1233** [comment]
我遇到了相同的问题，可以推荐下哪里下到作者用的原始的llama权重吗

**Comment by FloatingIsland2** [comment]
> 重新检查你原始llama的权重
用以下hf 权重https://huggingface.co/nyanko7/LLaMA-7B/tree/main，BiLLa-7B-LLM同样出现AssertionError: The sum of weights (-3801.82958984375) is wrong.
 有推荐的正确初始权重吗？

**Comment by FloatingIsland2** [comment]
用以下hf 权重：https://huggingface.co/nyanko7/LLaMA-7B/tree/main，BiLLa-7B-LLM同样出现AssertionError: The sum of weights (-3801.82958984375) is wrong.
有推荐的正确初始权重吗？

**Comment by FloatingIsland2** [comment]
> 重新检查你原始llama的权重

用以下llama初始权重https://huggingface.co/nyanko7/LLaMA-7B/tree/main，同样出错
AssertionError: The sum of weights (-3801.82958984375) is wrong.
有推荐的正确初始权重吗？

另外6.1发现作者更新了embedding_convert.py中的求和部分，现在可以跳过求和部分直接转换，这样是否正确？

**Comment by Neutralzz** [comment]
> > 重新检查你原始llama的权重
> 
> 用以下llama初始权重[https://huggingface.co/nyanko7/LLaMA-7B/tree/main，同样出错](https://huggingface.co/nyanko7/LLaMA-7B/tree/main%EF%BC%8C%E5%90%8C%E6%A0%B7%E5%87%BA%E9%94%99) AssertionError: The sum of weights (-3801.82958984375) is wrong. 有推荐的正确初始权重吗？
> 
> 另外6.1发现作者更新了embedding_convert.py中的求和部分，现在可以跳过求和部分直接转换，这样是否正确？

否，如果是转换SFT模型，求和结果必须等于代码中EMBED_SUM的结果。
