### ISSUE TITLE
请问fastchat如何运行？

### ISSUE THREAD

**Issue by hopeforus** [Neutralzz/BiLLa#14]

**Comment by Neutralzz** [comment]
用他们的Command Line Inference，指定model-path到BiLLa-7B-SFT的模型路径即可。

**Comment by hopeforus** [comment]
我用这个命令，出现如下的错误： python -m fastchat.serve.cli --model-path /home/hope/work/Chinese-Vicuna/models/BiLLa-7B-SFT
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/runpy.py:196 in _run_module_as_main              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/runpy.py:86 in _run_code                         │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/fastchat/serve/cli.py:159 in       │
│ <module>                                                                                         │
│                                                                                                  │
│   156 │   │   help="Print useful debug information (e.g., prompts)",                             │
│   157 │   )                                                                                      │
│   158 │   args = parser.parse_args()                                                             │
│ ❱ 159 │   main(args)                                                                             │
│   160                                                                                            │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/fastchat/serve/cli.py:121 in main  │
│                                                                                                  │
│   118 │   else:                                                                                  │
│   119 │   │   raise ValueError(f"Invalid style for console: {args.style}")                       │
│   120 │   try:                                                                                   │
│ ❱ 121 │   │   chat_loop(                                                                         │
│   122 │   │   │   args.model_path,                                                               │
│   123 │   │   │   args.device,                                                                   │
│   124 │   │   │   args.num_gpus,                                                                 │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/fastchat/serve/inference.py:244 in │
│ chat_loop                                                                                        │
│                                                                                                  │
│   241 │   debug: bool,                                                                           │
│   242 ):                                                                                         │
│   243 │   # Model                                                                                │
│ ❱ 244 │   model, tokenizer = load_model(                                                         │
│   245 │   │   model_path, device, num_gpus, max_gpu_memory, load_8bit, cpu_offloading, debug     │
│   246 │   )                                                                                      │
│   247 │   is_chatglm = "chatglm" in str(type(model)).lower()                                     │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/fastchat/model/model_adapter.py:15 │
│ 8 in load_model                                                                                  │
│                                                                                                  │
│   155 │                                                                                          │
│   156 │   # Load model                                                                           │
│   157 │   adapter = get_model_adapter(model_path)                                                │
│ ❱ 158 │   model, tokenizer = adapter.load_model(model_path, kwargs)                              │
│   159 │                                                                                          │
│   160 │   if (device == "cuda" and num_gpus == 1 and not cpu_offloading) or device == "mps":     │
│   161 │   │   model.to(device)                                                                   │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/fastchat/model/model_adapter.py:41 │
│ in load_model                                                                                    │
│                                                                                                  │
│    38 │   │   return True                                                                        │
│    39 │                                                                                          │
│    40 │   def load_model(self, model_path: str, from_pretrained_kwargs: dict):                   │
│ ❱  41 │   │   tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)              │
│    42 │   │   model = AutoModelForCausalLM.from_pretrained(                                      │
│    43 │   │   │   model_path, low_cpu_mem_usage=True, **from_pretrained_kwargs                   │
│    44 │   │   )                                                                                  │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/models/auto/tokenizat │
│ ion_auto.py:702 in from_pretrained                                                               │
│                                                                                                  │
│   699 │   │   │   │   raise ValueError(                                                          │
│   700 │   │   │   │   │   f"Tokenizer class {tokenizer_class_candidate} does not exist or is n   │
│   701 │   │   │   │   )                                                                          │
│ ❱ 702 │   │   │   return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *input   │
│   703 │   │                                                                                      │
│   704 │   │   # Otherwise we have to be creative.                                                │
│   705 │   │   # if model is an encoder decoder, the encoder tokenizer class is used by default   │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/tokenization_utils_ba │
│ se.py:1811 in from_pretrained                                                                    │
│                                                                                                  │
│   1808 │   │   │   else:                                                                         │
│   1809 │   │   │   │   logger.info(f"loading file {file_path} from cache at {resolved_vocab_fil  │
│   1810 │   │                                                                                     │
│ ❱ 1811 │   │   return cls._from_pretrained(                                                      │
│   1812 │   │   │   resolved_vocab_files,                                                         │
│   1813 │   │   │   pretrained_model_name_or_path,                                                │
│   1814 │   │   │   init_configuration,                                                           │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/tokenization_utils_ba │
│ se.py:1965 in _from_pretrained                                                                   │
│                                                                                                  │
│   1962 │   │                                                                                     │
│   1963 │   │   # Instantiate tokenizer.                                                          │
│   1964 │   │   try:                                                                              │
│ ❱ 1965 │   │   │   tokenizer = cls(*init_inputs, **init_kwargs)                                  │
│   1966 │   │   except OSError:                                                                   │
│   1967 │   │   │   raise OSError(                                                                │
│   1968 │   │   │   │   "Unable to load vocabulary from file. "                                   │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/models/llama/tokeniza │
│ tion_llama.py:96 in __init__                                                                     │
│                                                                                                  │
│    93 │   │   self.add_bos_token = add_bos_token                                                 │
│    94 │   │   self.add_eos_token = add_eos_token                                                 │
│    95 │   │   self.sp_model = spm.SentencePieceProcessor(**self.sp_model_kwargs)                 │
│ ❱  96 │   │   self.sp_model.Load(vocab_file)                                                     │
│    97 │                                                                                          │
│    98 │   def __getstate__(self):                                                                │
│    99 │   │   state = self.__dict__.copy()                                                       │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/sentencepiece/__init__.py:905 in   │
│ Load                                                                                             │
│                                                                                                  │
│    902 │   │   raise RuntimeError('model_file and model_proto must be exclusive.')               │
│    903 │     if model_proto:                                                                     │
│    904 │   │   return self.LoadFromSerializedProto(model_proto)                                  │
│ ❱  905 │     return self.LoadFromFile(model_file)                                                │
│    906                                                                                           │
│    907                                                                                           │
│    908 # Register SentencePieceProcessor in _sentencepiece:                                      │
│                                                                                                  │
│ /home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/sentencepiece/__init__.py:310 in   │
│ LoadFromFile                                                                                     │
│                                                                                                  │
│    307 │   │   return _sentencepiece.SentencePieceProcessor_serialized_model_proto(self)         │
│    308 │                                                                                         │
│    309 │   def LoadFromFile(self, arg):                                                          │
│ ❱  310 │   │   return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)              │
│    311 │                                                                                         │
│    312 │   def _EncodeAsIds(self, text, enable_sampling, nbest_size, alpha, add_bos, add_eos, r  │
│    313 │   │   return _sentencepiece.SentencePieceProcessor__EncodeAsIds(self, text, enable_sam  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by hopeforus** [comment]
用你推荐的程序，出现如下错误： tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 642, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 486, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/hope/miniconda3/envs/dbgpt/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '/BiLLa-7B-SFT'.

**Comment by hopeforus** [comment]
已经解决 模型配置文件的问题
