### ISSUE TITLE
关于sft阶段loss数值的问题

### ISSUE THREAD

**Issue by lucasjinreal** [Neutralzz/BiLLa#18]
用train3.5M来训练第二阶段产出的预训练模型，loss一开始是9，训练一段时间后变成5，请问这个数值是否符合预期？大概多少差不多收敛啊？

**Comment by Neutralzz** [comment]
sft最后是收敛到0.55左右，开始几百步的时候印象里应该是3到5左右（log文件没带走，所以具体数值我也不记得了

**Comment by lucasjinreal** [comment]
我这个0.03个epoch到1.8就下不去了啊。`没带走` 意思是从实习公司开溜了？

**Comment by Neutralzz** [comment]
> 我这个0.03个epoch到1.8就下不去了啊。`没带走` 意思是从实习公司开溜了？

不是实习哦，之前就是你厂的正式。
