### ISSUE TITLE
作者您好！请问是否能提供从huggingface的llama7b合并权重的代码？

### ISSUE THREAD

**Issue by yzxyzh** [Neutralzz/BiLLa#19]
作者您好！我非常希望尝试使用您的模型，但是我这里只有hf的7b base模型，没有原版的。请问是否能提供一个从hf 7b模型转换的脚本呢？

**Comment by Neutralzz** [comment]
其实用同一套代码就能支持。
meta_llama_pth_file的文件路径是包含embedding的那个hf的bin文件

**Comment by nlp4whp** [comment]
> 作者您好！我非常希望尝试使用您的模型，但是我这里只有hf的7b base模型，没有原版的。请问是否能提供一个从hf 7b模型转换的脚本呢？

作者开放的和hf原版的只在`pytorch_model-33-of-33.bin`有区别
