### ISSUE TITLE
预训练纯文本Loss问题请教

### ISSUE THREAD

**Issue by DSXiangLi** [Neutralzz/BiLLa#22]
针对Causal LM Loss一直有一个困惑，就是以下两种方式的差异有多少
1. 随机MASK前半部分，就是您代码中的部分
input_ids = self.tokenizer.encode(example['input'])[:self.max_seq_length]
pos = random.randint(int(0.2 * len(input_ids)) + 1, int(0.7 * len(input_ids)))
loss_mask = [0] * pos + [1] * (len(input_ids) - pos)

2. 完全不MASK，直接对整个文本计算Loss，例如Hhuggingface提供的clm示例中
result["labels"] = result["input_ids"].copy() https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py

想请教下这两种方案在预训练阶段会有哪些差异？个人感觉是第一种方案可以避免前半一段token因为上文太少，生成不准影响loss的问题，但又看到很多实现是第二种方案。

**Comment by DSXiangLi** [comment]
@Neutralzz 感谢回复，我也是这么想的，以及会和之后的指令微调更容易进行混合训练。那我自己再做下消融尝试下不同的mask位置的差异吧。感谢~

**Comment by forceshorty** [comment]
> 我是同样考虑了这一点，选择了方案一。这样训练的模型可能更强依赖于prefix，而不是内化的knowledge。
@Neutralzz @DSXiangLi 
请问这个怎么理解?
我的理解是SFT时只针对output计算loss, 这种方式与推理是对齐的

**Comment by DSXiangLi** [comment]
> 
上面讨论的是预训练不是SFT的部分

**Comment by forceshorty** [comment]
> 这样训练的模型可能更强依赖于prefix，而不是内化的knowledge。


了解, 那预训练这块能否麻烦解释一下这句话
提到SFT, 是因为看到不同的模型在SFT时也有不同的loss计算方式, 有的只对ouput算, 有的所有token算, 也存在疑问~

**Comment by DSXiangLi** [comment]
> > 这样训练的模型可能更强依赖于prefix，而不是内化的knowledge。
> 
> 了解, 那预训练这块能否麻烦解释一下这句话 提到SFT, 是因为看到不同的模型在SFT时也有不同的loss计算方式, 有的只对ouput算, 有的所有token算, 也存在疑问~
> 

哈哈估计是同被llama还是alpaca的代码迷幻到了，有个train_on_input的字段。我个人认为SFT应该只对输出计算loss，两个方面
1. 过拟合：我们对比过SFT对input计算loss和只对output计算loss的，整体上如果你对input也计算loss了很容易对模板化的prompt输入(例如####Instruction)过拟合, 因为这部分token在每个样本中都存在所以被模型过度更新（记忆）了，一旦模板不匹配，或者你的内容中有和模板相似的内容，会影响解码。l
2. 一致性：就是上面你提到的训练和推理的一致性问题。对指令样本来说推理是条件生成任务，如果对input也计算loss就是无条件生成任务了，其实是不一致的。

**Comment by forceshorty** [comment]
> 这样训练的模型可能更强依赖于prefix，而不是内化的knowledge。

再请教一下, 这句话该如何理解, input是否计算loss会影响使用的knowledge模式吗
@DSXiangLi  @Neutralzz
