### ISSUE TITLE
打算在开源的BiLLa模型上继续训练，模型转换有困难

### ISSUE THREAD

**Issue by jiezhangGt** [Neutralzz/BiLLa#24]
大佬你好，请问我如果打算在开源的BiLLa模型上继续训练，需要将BiLLa模型进行反向操作转换成llama的原始格式才能进行吗？如果是的换，转换脚本请问有现成的开源的吗？谢谢

**Comment by Neutralzz** [comment]
https://github.com/huggingface/transformers/blob/v4.28.1/src/transformers/models/llama/convert_llama_weights_to_hf.py#L122

你看它L122和L197从loaded到state_dict的过程，反过来就可以了。

**Comment by jiezhangGt** [comment]
> 

好的。请问只转换state_dict就可以了吗？tokenizer.model需不需要转换？还是直接用BiLLa模型的tokenizer.model就可以了吗？谢谢大佬，盼复

**Comment by jiezhangGt** [comment]
> 直接用BiLLa的tokenizer.model

好的！多谢大佬！大佬，请问环境必须是Python >= 3.8吗？python3.7可不可以呀？

**Comment by satisic** [comment]
大佬你好，我也打算基于目前开源的Billa继续训练，请问有支持finetune吗，全量训练的话个人的硬件有些不足ovo

**Comment by jiezhangGt** [comment]
> 大佬你好，我也打算基于目前开源的Billa继续训练，请问有支持finetune吗，全量训练的话个人的硬件有些不足ovo

我计划在Billa继续全量参数微调看看效果

**Comment by Neutralzz** [comment]
python3.7应该也可以，但我只试过3.8和3.10，不敢保证。另外本项目代码仅供参考，HF格式的权重已放出，使用其他训练框架或工具也会很方便。
