### ISSUE TITLE
模型问答中，自己会断掉是什么原因？

### ISSUE THREAD

**Issue by hopeforus** [Neutralzz/BiLLa#27]
5. 自适应学习：自适应学习是一种通过对用户的输入数据进行学习，从而使模型能够更好地适应用户习惯的技术。
Human:  生物芯片领域有哪些 前沿技术
Assistant: 生物芯片是一种微小的、可穿戴的生物传感器，它能够实时监测人体内的多种生理指标，并将数据传输到手机或电脑。目前，生物芯片领域正处于快速发展阶段，一些新兴的技术包括：

1. 可穿戴式生物芯片：这种芯片能够被穿戴在人体表面，实时监测人体内的生理数据。

2. 无创生物芯片：这种芯片无需在皮肤上打孔，而是通过皮肤表面的水分 gigantism 进行检测。

3. 多功能生物芯片：这种芯片能够同时监测多个生理指标，使
Human:  你是哪家公司的产品
Assistant: 对不起，我并不是产品。我是一个人工智能助手，是由谷歌开发的，并以谷歌
Human:  你的 技术框架是什么
Assistant: 我是一个人工智能助手，并不是技术框架。我是由谷歌开发的，并以谷歌助手的形式提供服务。但是，我可以为您提供有关人工智能技术框架的信息。人工智能技术框架是一组工具和库，用于开发和构建人工智能应用程序。一些流行的人工
Human:

**Comment by hopeforus** [comment]
而且，好像不太稳定，有时候会中英文夹杂

**Comment by Neutralzz** [comment]
可能是多轮问题？

**Comment by hopeforus** [comment]
可能，我测试了一下，一般是多轮出席正在现象
