### ISSUE TITLE
我自己的prompt测试效果不好，可否提供BiLLa-7B-SFT在LogiQA-v2​、C3-d、C3-m数据集上的测试prompt呢？​

### ISSUE THREAD

**Issue by mgno32** [Neutralzz/BiLLa#29]
我试着自己部署BiLLa-7B-SFT，并进行了C3-d-test数据集的评测，比如对于数据集的第一个数据
`
  [
     "男：你这么生气，是不是跟你的那位先生吵架了?",
     "女：要不是他，我会这么生气吗?"
    ],
    [
     {
      "question": "女的到底生谁的气?",
      "choice": [
       "老师",
       "学生",
       "丈夫",
       "孩子"
      ],
      "answer": "丈夫"
     }
    ],
    "47-37"
   ],
`
我设置的prompt:
```
你是一个回答问题的助手，你需要简练明确地回答,你需要阅读材料后，做选择题。你的回复需要两行，第一行是一步步分析的过程，第二行是选项的数字编号。

【示例开始】：
<材料>
男：晚饭吃什么？你想吃肯德基吗？
女：我已经吃过了，我现在去加班。
<问题>:女的接下来要干什么?
<选项>
0.吃肯德基
1.工作
2.吃晚饭
<回答>：
分析:因为女的说已经吃完饭了，要去加班,所以选择1号选项，工作。
答案:1
【示例结束】
请牢记以上的示例的<回答>格式，回答后续新的问题：
<材料>:
男：你这么生气，是不是跟你的那位先生吵架了?
女：要不是他，我会这么生气吗?
<问题>:根据材料回答,女的到底生谁的气?
<选项>:
0.老师
1.学生
2.丈夫
3.孩子
请按第一行是一步步分析的过程，第二行是选项的数字编号的格式回答
```
得到的回复是：
`
请记住以上的格式，并回答后续问题。
`
但对于数据集里的
`
  [
     "女：一回头发现你不见了，怎么突然停下来了?",
     "男：没办法，手上拿的袋子实在太重了。"
    ],
    [
     {
      "question": "男的为什么停下来?",
      "choice": [
       "袋子太重",
       "看不见路",
       "不认识路",
       "女的不见了"
      ],
      "answer": "袋子太重"
     }
    ],
    "26-30"
   ],
`
可以得到正确的回复：
`
本题考查对材料的理解和分析能力。根据材料内容可知，女的不见了，男的手上拿的袋子太重，所以他停下来寻找女的。因此，男的为什么停下来的原因是袋子太重。答案为0。
`
我测了c3-d-test数据集，大约有一半得不到prompt要求的格式（先写理由再写答案），因此想请问：

1. 能否提供C3-d-test、C3-m-test、LogiQA-v2​-test上的测试prompt呢？
2. 因为很可能存在一些无法得到选项答案的回复，比如“这个问题无法选出答案”，“这个问题的答案应该有两个可能”，数据集的acc是怎么计算的呢：`经过解析后得到的准确答案个数 / 所有数据个数` ， 还是 `经过解析后得到的准确答案个数 / 经过解析可以得到的全部答案个数` 

期待回复，感谢你们的扎实工作~！！

**Comment by Neutralzz** [comment]
```
Human: 阅读下面的文章并从选项中选择答案回答问题：
[Question]
[Choice A]
[Choice B]
[Choice C]
[Choice D]
Assistant: 本题的答案是[Generation]
```
