### ISSUE TITLE
训练代码和数据会开源吗

### ISSUE THREAD

**Issue by renmada** [Neutralzz/BiLLa#3]
大佬很棒的工作！想学习一下整个训练的流程

**Comment by Neutralzz** [comment]
如果模型的效果不是错觉的话，是打算开源代码的。

但数据开源可能麻烦点，因为原始数据都是别人开源的。

**Comment by Kouuh** [comment]
> 如果模型的效果不是错觉的话，是打算开源代码的。
> 
> 但数据开源可能麻烦点，因为原始数据都是别人开源的。

想问下全参数更新是要多少硬件资源以及训练多久？

**Comment by Neutralzz** [comment]
@Kouuh  Colossalai训练框架，8卡V100，batch size 160，4000+ gpu hours

**Comment by zbbwss** [comment]
大佬训练代码 可以开源下！

**Comment by jhg543** [comment]
> 如果模型的效果不是错觉的话，是打算开源代码的。
> 
> 但数据开源可能麻烦点，因为原始数据都是别人开源的。

请问第二阶段用的开源数据都有哪几个数据集？

**Comment by renmada** [comment]
> 如果模型的效果不是错觉的话，是打算开源代码的。
> 
> 但数据开源可能麻烦点，因为原始数据都是别人开源的。

如果是这样，方便给点各阶段训练数据的样例吗。参考大佬的格式直接自己构造数据

**Comment by Neutralzz** [comment]
> > 如果模型的效果不是错觉的话，是打算开源代码的。
> > 但数据开源可能麻烦点，因为原始数据都是别人开源的。
> 
> 如果是这样，方便给点各阶段训练数据的样例吗。参考大佬的格式直接自己构造数据

可以，这周有点忙，周末看情况把代码和数据样例开源出来。

**Comment by AceCHQ** [comment]
> > > 如果模型的效果不是错觉的话，是打算开源代码的。
> > > 但数据开源可能麻烦点，因为原始数据都是别人开源的。
> > 
> > 
> > 如果是这样，方便给点各阶段训练数据的样例吗。参考大佬的格式直接自己构造数据
> 
> 可以，这周有点忙，周末看情况把代码和数据样例开源出来。

同求！！

**Comment by Neutralzz** [comment]
已开源，先关闭issue了
_（单休还在周日熬夜，我怕不是要x）_
