### ISSUE TITLE
请问这段代码的作用是什么？

### ISSUE THREAD

**Issue by royshan** [Neutralzz/BiLLa#31]
非常感谢开源这个独特的项目！

在 task_instruct_tuning_main.py中有如下代码：
                input_ids_1 = self.tokenizer.encode(prefix, True, False)
                loss_mask_1 = [0] * len(input_ids_1)
                input_ids_2 = self.tokenizer.encode(example['output'], False, True)
                loss_mask_2 = [1] * len(input_ids_2)
                input_ids = input_ids_1 + input_ids_2
                loss_mask = loss_mask_1 + loss_mask_2
                input_ids = input_ids[:self.max_seq_length]
                loss_mask = loss_mask[:self.max_seq_length]

请问其作用是什么？是在计算loss时屏蔽掉指令和输入部分，只计入输出部分，对吗？

还有：
                input_ids = self.tokenizer.encode(example["input"])[:self.max_seq_length]
                pos = random.randint(int(0.2 * len(input_ids)) + 1, int(0.7 * len(input_ids)))
                loss_mask = [0] * pos + [1] * (len(input_ids) - pos)

这部分使用动态的条件生成任务，对吗？这样的设计考虑是什么？

**Comment by Neutralzz** [comment]
1. 是
2. 对于预训练语料，并不确定应该从哪里截断做条件生成，所以随机取。

**Comment by royshan** [comment]
谢谢！
