### ISSUE TITLE
有计划训练/发布13B参数的类似模型嘛

### ISSUE THREAD

**Issue by mblank5** [Neutralzz/BiLLa#4]
看之前issue，好像只有8卡训练，13B的话可能需要的资源和时间更长，不知道还有可能性训练和发布不？

**Comment by Neutralzz** [comment]
> 看之前issue，好像只有8卡训练，13B的话可能需要的资源和时间更长，不知道还有可能性训练和发布不？

暂不考虑

**Comment by whalefa1I** [comment]
> > 看之前issue，好像只有8卡训练，13B的话可能需要的资源和时间更长，不知道还有可能性训练和发布不？
> 
> 暂不考虑

我倒是有卡，要不我来，挂你项目下面

**Comment by puppet101** [comment]
支持

**Comment by Neutralzz** [comment]
问题已整理在FAQ，如有其他问题可再打开或开新issue~
