### ISSUE TITLE
请问作者，第一阶段的二次预训练数据大概一共用了多少呢？

### ISSUE THREAD

**Issue by HalcyonLiang** [Neutralzz/BiLLa#6]
RT

**Comment by Neutralzz** [comment]
@HalcyonLiang 1600w。Batch size 160，训练10w步，因为一轮都没有训完，所以数据基本没有重复训练。

**Comment by piekey1994** [comment]
> @HalcyonLiang 1600w。Batch size 160，训练10w步，因为一轮都没有训完，所以数据基本没有重复训练。

实际chatgpt生成数据量是有800w那么多吗

**Comment by daisy-belle** [comment]
> @HalcyonLiang 1600w。Batch size 160，训练10w步，因为一轮都没有训完，所以数据基本没有重复训练。

您好请问 这不是正好训练了一轮吗，训练完后如何评估训练的效果呢，还是只看loss？多谢哈

**Comment by Neutralzz** [comment]
@daisy-belle 代码和参数已开源，context 1024，第一二阶段评估看perplexity，第三阶段看loss挑的checkpoint（但仍然是训练到最后的模型）
