### ISSUE TITLE
请问为什么增量预训练采用了两个阶段，第二个阶段提升大吗？

### ISSUE THREAD

**Issue by AceCHQ** [Neutralzz/BiLLa#7]
您好，感谢您的工作。请教您两个问题：
1、我想请问预训练增强分为两个阶段的原因
2、第二个阶段提升大吗？采用的数据集的名称是哪些？

再次感谢

**Comment by Neutralzz** [comment]
> 您好，感谢您的工作。请教您两个问题： 1、我想请问预训练增强分为两个阶段的原因 2、第二个阶段提升大吗？采用的数据集的名称是哪些？
> 
> 再次感谢

@AceCHQ 因为想提升语言模型更懂任务、更懂逻辑，用到的开源数据后续会写在README

**Comment by Neutralzz** [comment]
问题已整理到FAQ，如有疑问可再打开~
