### ISSUE TITLE
推理速度较慢

### ISSUE THREAD

**Issue by Expert68** [Neutralzz/BiLLa#9]
作者大大你好，你的这个模型相比于其他llama模型推理速度要慢，然后占用显存也明显要高，这个是什么原因导致的，有解决办法吗。目前测试下来模型在大部分场景都ok。

**Comment by Neutralzz** [comment]
除了词表扩充外，没有其他地方会给llama带了参数量的增加。优化推理部署这块对我来说超纲了。
